stc: signal_test.c
	clang -o $@ $<
shs: sh_sleep.c
	clang -o $@ $<
gts: get_terminal_size.c
	clang -o $@ $<
saor: stdin_and_out_redirect.c
	clang -o $@ $<
sm: sig_mask.c
	clang -o $@ $<
st: sleep_test.c
	clang -o $@ $<
hqs: high_quality_sleep.c
	clang -o $@ $<
cns: clock_ns.c
	clang -o $@ $<
sntn: signal_number_to_name.c
	clang -o $@ $<
